CREATE TABLE "stratum_briefs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"queried_company_name" text NOT NULL,
	"matched_company_name" text NOT NULL,
	"ats_source_used" text,
	"result_state" text NOT NULL,
	"company_match_confidence" text NOT NULL,
	"company_match_explanation" text NOT NULL,
	"source_coverage_completeness" text NOT NULL,
	"source_coverage_explanation" text NOT NULL,
	"watchlist_read_label" text NOT NULL,
	"watchlist_read_summary" text NOT NULL,
	"watchlist_read_confidence" text NOT NULL,
	"watchlist_read_explanation" text NOT NULL,
	"proof_role_grounding" text NOT NULL,
	"proof_role_grounding_explanation" text NOT NULL,
	"jobs_observed_count" integer NOT NULL,
	"proof_roles_snapshot" jsonb NOT NULL,
	"limits_snapshot" jsonb NOT NULL,
	"result_snapshot" jsonb NOT NULL,
	"unsupported_source_pattern" text,
	"provider_failures" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
